/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./index.html"],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#9ffa43",
        "on-primary": "#1c3700",
        "surface-container-low": "#1a1c1c",
        "on-tertiary-fixed-variant": "#474746",
        "on-primary-fixed": "#0e2000",
        "error-container": "#93000a",
        "on-surface-variant": "#c0cab0",
        "on-secondary-fixed": "#1c1b1b",
        "surface-dim": "#121414",
        secondary: "#c8c6c5",
        "on-tertiary": "#303030",
        "inverse-on-surface": "#2f3131",
        "secondary-fixed": "#e5e2e1",
        "on-primary-fixed-variant": "#2a5000",
        "on-secondary-fixed-variant": "#474746",
        outline: "#8a947c",
        "on-primary-container": "#3e7100",
        "on-secondary": "#313030",
        "secondary-container": "#474746",
        "on-background": "#e2e2e2",
        "surface-container": "#1e2020",
        "on-secondary-container": "#b7b5b4",
        "tertiary-container": "#e4e2e1",
        "surface-container-lowest": "#0c0f0f",
        tertiary: "#ffffff",
        "inverse-surface": "#e2e2e2",
        "tertiary-fixed-dim": "#c8c6c5",
        "secondary-fixed-dim": "#c8c6c5",
        surface: "#121414",
        error: "#ffb4ab",
        "tertiary-fixed": "#e4e2e1",
        "primary-container": "#9ffa43",
        "outline-variant": "#404a36",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#1b1c1c",
        "surface-bright": "#37393a",
        "surface-variant": "#333535",
        "surface-tint": "#84dd23",
        "on-tertiary-container": "#656464",
        primary: "#ffffff",
        "surface-container-highest": "#333535",
        "on-surface": "#e2e2e2",
        "on-error": "#690005",
        "inverse-primary": "#3a6a00",
        "primary-fixed-dim": "#84dd23",
        "surface-container-high": "#282a2b",
        background: "#121414",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "section-padding": "120px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "grid-margin": "40px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "label-caps": ["JetBrains Mono"],
        "body-md": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "600" }],
        "display-lg": [
          "72px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "600" },
        ],
        "label-caps": [
          "12px",
          {
            lineHeight: "1.0",
            letterSpacing: "0.1em",
            fontWeight: "500",
          },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
  ],
};
